### ISSUE TITLE
Align & Justify Tracks

### ISSUE THREAD

**Issue by stwrt** [stwrt/WebKit#1]
## PRs
- https://github.com/WebKit/WebKit/pull/7420
- https://github.com/WebKit/WebKit/pull/8306

## TODO
- [x] consume align tracks
- [x] consume justify tracks
- [x] convert align tracks
- [x] convert justify tracks
- [x] computed style extractor align tracks
- [x] computed style extractor justify tracks
- [x] check the align tracks and justify tracks accepted values
- [x] Fix bug with get computed style not returning proper values. (Shows up properly in WebInspector though 🤔)
- [ ] Add support for animations
- [ ] Masonry Align and Justify Tracks Serialization

**Comment by stwrt** [comment]
Align-Tracks is looking in pretty good shape, and just has the computed style to complete.

For Justify-Tracks I need to go back and cleanup the possible options, and then add the conversion code like Align-Tracks.

**Comment by stwrt** [comment]
Had to do some major refactoring of the patch to use existing infrastructure in place. It is ready to land now though.

Still have a few remaining bugs to sift through (mentioned above), but they should not be blockers.

**Comment by yisibl** [comment]
Nice work!
